#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

cd $(dirname $0)/..

echo "#!/bin/sh" > ./dist/publish.sh
chmod 755 ./dist/publish.sh
echo "github-release release --user niusmallnan --repo ros-wait-for --tag ${VERSION} --pre-release" >> ./dist/publish.sh
echo "github-release upload --user niusmallnan --repo ros-wait-for --tag ${VERSION} --file ./bin/ros-wait-for --name ros-wait-for" >> ./dist/publish.sh

